name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "master"

      # Used to host cibuildwheel
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install python-semantic-release
        run: pipx install python-semantic-release==7.34.6

      - name: Get Release Tag
        id: release_tag
        shell: bash
        run: |
          echo "::set-output name=newest_release_tag::$(semantic-release print-version --current)"

      - uses: actions/checkout@v3
        with:
          ref: "${{ steps.release_tag.outputs.newest_release_tag }}"
          fetch-depth: 0

      - name: Build pure wheel
        if: runner.os == 'Linux'
        run: |
          pip install build
          cp pyproject.toml pyproject.toml.bak
          sed -i -E -e '/\[tool.poetry.build\]/,/^$/d' pyproject.toml
          python -m build --wheel --outdir ./wheelhouse .
          mv pyproject.toml.bak pyproject.toml

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
